// AUTO-GENERATED by scripts/gen-posts-index.mjs — do not edit by hand.
// Registry of all ported Wix blog posts, served at /post/<slug>.
import type { BlogPost } from "@/lib/blog-types";
import { post as p0 } from './10-health-and-beauty-benefits-of-brown-rice';
import { post as p1 } from './acne-scar-treatment-malta';
import { post as p2 } from './aesthetic-treatments-men-are-loving-this-summer';
import { post as p3 } from './anti-ageing-treatments-malta';
import { post as p4 } from './back-from-the-beach-give-your-skin-the-love-it-deserves';
import { post as p5 } from './banishing-acne-scars-the-best-treatments-for-flawless-skin-this-summer';
import { post as p6 } from './banishing-sunspots-aesthetic-treatments-to-even-your-summer-skin-tone';
import { post as p7 } from './beauty-she-ll-love-the-ultimate-mother-s-day-aesthetic-gift-guide';
import { post as p8 } from './botox-malta-guide';
import { post as p9 } from './bridal-beauty-the-aesthetic-treatments-to-book-before-i-do';
import { post as p10 } from './bridal-glow-must-have-aesthetic-treatments-for-the-perfect-wedding-day-look';
import { post as p11 } from './can-you-get-botox-in-summer-spoiler-yes';
import { post as p12 } from './can-you-get-fillers-in-summer-everything-you-should-know';
import { post as p13 } from './cheek-fillers-malta';
import { post as p14 } from './cleanse-and-renew-the-essential-summer-skin-detox-for-autumn-prep';
import { post as p15 } from './cosmetic-injections-everything-you-need-to-know-about-botox-and-fillers';
import { post as p16 } from './debunking-common-myths-about-botox-and-fillers';
import { post as p17 } from './dermal-fillers-malta-guide';
import { post as p18 } from './enhance-your-summer-look-natural-beauty-boosting-treatments-you-ll-love';
import { post as p19 } from './erase-the-tired-look-aesthetic-treatments-to-revive-your-eyes';
import { post as p20 } from './flawless-skin-for-all-your-summer-memories';
import { post as p21 } from './glp-1-weight-loss-treatment-malta';
import { post as p22 } from './hifu-facial-treatment-malta';
import { post as p23 } from './hydration-volume-what-makes-hyaluronic-fillers-so-popular';
import { post as p24 } from './jawline-filler-malta';
import { post as p25 } from './laser-hair-removal-malta-complete-guide';
import { post as p26 } from './lift-and-tighten-non-surgical-skin-tightening-treatments-explained';
import { post as p27 } from './lip-trends-2025-what-s-hot-this-summer';
import { post as p28 } from './microneedling-this-summer-yes-or-no';
import { post as p29 } from './natural-beauty-tweaks-you-ll-adore-this-summer';
import { post as p30 } from './natural-lip-fillers-malta-trends';
import { post as p31 } from './new-year-new-me-a-sophisticated-approach-to-skin-confidence-through-aesthetic-care';
import { post as p32 } from './non-invasive-facial-contouring-sculpt-your-perfect-summer-look';
import { post as p33 } from './non-surgical-achieve-your-summer-body-goals';
import { post as p34 } from './not-just-a-moisturiser-the-injectable-glow-booster-you-need';
import { post as p35 } from './pigmentation-treatment-malta';
import { post as p36 } from './prp-facial-malta';
import { post as p37 } from './revive-your-skin-after-vacation-best-aesthetic-treatments-to-renew-your-glow';
import { post as p38 } from './russian-lips-structure-volume-elegance';
import { post as p39 } from './skin-boosters-radiant-hydrated-skin';
import { post as p40 } from './smooth-for-summer-why-spring-is-the-best-time-to-start-laser-hair-removal';
import { post as p41 } from './stay-ahead-emerging-aesthetic-procedures-to-consider';
import { post as p42 } from './summer-microneedling-what-to-know-before-you-book';
import { post as p43 } from './summer-skin-survival-essential-tips-to-protect-heal-and-glow';
import { post as p44 } from './tear-trough-filler-malta';
import { post as p45 } from './the-best-beauty-treatments-to-repair-and-regenerate-your-skin';
import { post as p46 } from './the-must-know-aesthetic-trends-for-august';
import { post as p47 } from './the-science-behind-non-surgical-facelifts';
import { post as p48 } from './the-secret-to-summer-skin-start-in-june';
import { post as p49 } from './under-eye-filler-faqs-everything-you-need-to-know';
import { post as p50 } from './why-summer-dehydration-happens';
import { post as p51 } from './year-round-glow-how-to-preserve-your-summer-skin-radiance';
import { post as p52 } from './youthful-skin-starts-here-collagen-boosting-aesthetic-treatments-this-summer';

export const POST_REGISTRY: Record<string, BlogPost> = {
  [p0.slug]: p0,
  [p1.slug]: p1,
  [p2.slug]: p2,
  [p3.slug]: p3,
  [p4.slug]: p4,
  [p5.slug]: p5,
  [p6.slug]: p6,
  [p7.slug]: p7,
  [p8.slug]: p8,
  [p9.slug]: p9,
  [p10.slug]: p10,
  [p11.slug]: p11,
  [p12.slug]: p12,
  [p13.slug]: p13,
  [p14.slug]: p14,
  [p15.slug]: p15,
  [p16.slug]: p16,
  [p17.slug]: p17,
  [p18.slug]: p18,
  [p19.slug]: p19,
  [p20.slug]: p20,
  [p21.slug]: p21,
  [p22.slug]: p22,
  [p23.slug]: p23,
  [p24.slug]: p24,
  [p25.slug]: p25,
  [p26.slug]: p26,
  [p27.slug]: p27,
  [p28.slug]: p28,
  [p29.slug]: p29,
  [p30.slug]: p30,
  [p31.slug]: p31,
  [p32.slug]: p32,
  [p33.slug]: p33,
  [p34.slug]: p34,
  [p35.slug]: p35,
  [p36.slug]: p36,
  [p37.slug]: p37,
  [p38.slug]: p38,
  [p39.slug]: p39,
  [p40.slug]: p40,
  [p41.slug]: p41,
  [p42.slug]: p42,
  [p43.slug]: p43,
  [p44.slug]: p44,
  [p45.slug]: p45,
  [p46.slug]: p46,
  [p47.slug]: p47,
  [p48.slug]: p48,
  [p49.slug]: p49,
  [p50.slug]: p50,
  [p51.slug]: p51,
  [p52.slug]: p52,
};

export * from "./helpers";
